import ContentBlock from "../components/content/contentblock";
import styles from "./page.module.css"


export default function BlogLandingPage() {

  const content =
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut luctus magna vitae mi molestie rhoncus. Maecenas at vehicula neque, vitae convallis dolor. Aenean hendrerit non lacus sit amet semper. Proin facilisis mattis mi, ac congue magna viverra vitae. Integer mollis lacus gravida leo fermentum rhoncus. Donec sit amet consectetur lectus. Pellentesque tempus diam ac leo varius venenatis. Curabitur et iaculis odio. Nullam ipsum nisi, dignissim at risus nec, pulvinar interdum sapien. Nunc porta mi eu elementum gravida.

Nulla et purus egestas, pellentesque odio a, tempus lorem. Phasellus sed vestibulum odio. Phasellus lacinia, est et tincidunt aliquam, dui libero consequat velit, imperdiet elementum nibh erat suscipit lacus. Nunc sodales condimentum mauris nec imperdiet. Pellentesque euismod sem posuere bibendum interdum. Curabitur elementum velit dolor, nec ornare tortor hendrerit non. Fusce nunc eros, consequat ac hendrerit non, tincidunt vel purus. Nullam eget mauris id nisl mattis pulvinar. Curabitur tincidunt elementum nibh, vitae cursus sapien fermentum vitae. Vestibulum est ante, hendrerit id mi non, molestie mollis ipsum.

Maecenas in ex sed odio fermentum ullamcorper nec sed felis. Suspendisse eu egestas felis, ut aliquam leo. In turpis felis, ultrices vitae sem eget, sagittis sagittis magna. Nulla vitae urna pharetra, ultrices purus nec, maximus enim. Quisque dapibus varius felis, quis volutpat odio euismod non. Fusce laoreet interdum dictum. In varius mi eget dui fringilla tincidunt. Nulla tincidunt tincidunt est, et sagittis massa lacinia sed. Aliquam ultricies orci vitae diam porttitor pellentesque. Maecenas non magna diam.

Aenean tincidunt purus et varius congue. Etiam vulputate, nisl sit amet pellentesque egestas, velit velit scelerisque sem, nec auctor velit lacus vitae orci. Proin aliquam congue consequat. Nullam vestibulum, nulla ac ultricies eleifend, tortor lorem dignissim ligula, finibus tempor massa leo vitae mauris. Integer ultrices mollis cursus. Phasellus dignissim a ex vitae condimentum. Aenean at tempor felis, et egestas ligula. Suspendisse purus magna, consequat non placerat id, tempus vitae lorem. Sed bibendum porttitor efficitur. Curabitur mattis massa vel eros interdum, at fringilla odio pharetra. Nulla fermentum efficitur laoreet. Maecenas nec gravida tortor.

Morbi tincidunt ex et nunc placerat, sed aliquam quam sagittis. Suspendisse risus lacus, pretium in nisi quis, auctor pulvinar mi. Suspendisse ac tristique ex. Quisque pretium dictum quam eget cursus. Aliquam ultrices mauris at pretium tincidunt. Quisque mattis ex a lorem facilisis fermentum. Aliquam venenatis nulla libero, luctus rutrum dui condimentum eget. Aenean quis nisi ut diam tempus porttitor eget id neque. Suspendisse lorem nulla, finibus vel tempus et, ullamcorper quis purus. Quisque id ipsum id odio dignissim faucibus et ut felis.

Sed interdum vel eros eget aliquet. Aenean congue congue ultrices. In elementum, leo eu ullamcorper auctor, nisl elit vehicula justo, ac aliquam nulla sem eget dui. Vivamus id laoreet arcu, sed cursus massa. Mauris interdum hendrerit enim quis dapibus. Integer ultricies tristique tortor eget facilisis. Nulla euismod turpis ex, non tristique lorem sagittis eget. Fusce sagittis volutpat scelerisque. Phasellus pellentesque lectus a lacus placerat fringilla. Fusce euismod feugiat massa, id dictum velit sagittis non.

Duis laoreet, dolor id dignissim tincidunt, ex nunc vestibulum libero, eu porttitor turpis neque vitae diam. In non laoreet augue. Quisque sed ligula purus. Sed sagittis a sem eget porta. Nullam nec sodales quam. Nunc et velit vehicula, bibendum tellus vel, molestie sapien. Nam ut leo mollis, pharetra nulla a, euismod neque. Duis pretium urna et dui consectetur condimentum. Donec sed facilisis purus.

Mauris ac ullamcorper nibh, in cursus metus. Phasellus a metus vitae turpis eleifend lacinia. Integer dignissim pretium velit id hendrerit. Proin vehicula nisi tincidunt tellus fringilla sollicitudin. Ut accumsan quis mi ut lacinia. Pellentesque quis nunc vestibulum, lobortis velit ut, tristique diam. Mauris ac aliquam augue.

Duis erat magna, efficitur ac consequat finibus, vulputate nec mi. Aliquam convallis nisi quis libero mattis ultricies. Donec accumsan sem vitae justo mattis, id ultrices turpis interdum. Curabitur iaculis est et semper molestie. Quisque tempus interdum pretium. Phasellus et mauris in quam euismod tempus. Nunc et lorem vel justo pulvinar aliquam. Cras dapibus urna a tempus facilisis. Duis non commodo nisl. Sed nec purus ac erat pharetra volutpat nec sit amet elit. Vivamus at porttitor dui. Curabitur dui nibh, viverra quis ipsum vitae, congue scelerisque nunc. Proin fringilla venenatis rutrum. Nulla lectus ex, semper non mi vel, ultricies aliquam ex. Duis a nisl quis metus pharetra molestie placerat quis elit. Duis eleifend odio ac risus sollicitudin condimentum.

Etiam in rutrum metus. Aliquam consectetur magna lectus, sagittis euismod purus hendrerit et. Pellentesque ut orci sit amet nisi varius aliquam ac ut dui. Suspendisse consectetur vulputate suscipit. Nulla ut mattis arcu. Integer justo odio, aliquet in pharetra et, mattis vel sem. Praesent viverra interdum pretium. Aenean elementum efficitur sodales. Nullam vestibulum leo odio.

Cras aliquam auctor venenatis. Donec ligula dolor, aliquet ut nisi at, malesuada viverra sapien. Vivamus in viverra sapien, at consequat nibh. Aliquam vestibulum in leo in dignissim. Cras eu hendrerit dolor, in euismod risus. Sed sollicitudin nulla eget augue eleifend, et aliquet diam sodales. Etiam vehicula, nisi a sagittis maximus, sapien tellus consectetur ipsum, volutpat fermentum turpis justo et magna. Fusce sodales interdum ex sed suscipit.

Etiam lacinia velit orci, ut placerat sem sollicitudin eget. In a imperdiet lacus, in ullamcorper erat. Sed posuere odio ut lorem egestas malesuada. Donec id libero tempus, commodo magna quis, vulputate purus. Morbi accumsan fringilla ante, quis bibendum orci fringilla et. Sed posuere consequat diam et mattis. Nunc sit amet augue porttitor, venenatis massa eu, faucibus justo. Morbi venenatis iaculis sem eget facilisis.

Nullam porta pharetra eros id euismod. Maecenas quis suscipit odio, a accumsan lorem. Mauris suscipit, eros ac hendrerit sagittis, felis lorem hendrerit ligula, id consectetur justo diam eget turpis. Vivamus scelerisque enim ut condimentum ultrices. Mauris tempus bibendum vehicula. Sed quis sapien rhoncus, mattis nisl eget, cursus ante. Vestibulum malesuada, ligula ut accumsan pharetra, nulla orci pellentesque risus, quis tempor neque tortor a mauris. Aliquam nec consectetur mi. Phasellus non quam eu ex facilisis malesuada quis id arcu. Nam sodales quam sit amet arcu varius feugiat non ut nisi. Sed turpis orci, molestie vulputate orci sit amet, sollicitudin malesuada ex. Praesent condimentum velit sit amet nunc fermentum porttitor. Cras est nisi, pretium in sapien varius, imperdiet vehicula lectus. Suspendisse faucibus est eget pharetra vulputate.

Integer rutrum mauris vehicula lobortis ornare. Vivamus vehicula velit ac sodales interdum. Duis sem ipsum, volutpat at tempus vel, ullamcorper egestas risus. Pellentesque pretium nisi in commodo iaculis. Fusce consectetur ligula in vestibulum condimentum. Pellentesque eget bibendum sem. In hac habitasse platea dictumst. Curabitur placerat pellentesque nisi, sed imperdiet metus. Duis ornare augue ipsum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut luctus magna vitae mi molestie rhoncus. Maecenas at vehicula neque, vitae convallis dolor. Aenean hendrerit non lacus sit amet semper. Proin facilisis mattis mi, ac congue magna viverra vitae. Integer mollis lacus gravida leo fermentum rhoncus. Donec sit amet consectetur lectus. Pellentesque tempus diam ac leo varius venenatis. Curabitur et iaculis odio. Nullam ipsum nisi, dignissim at risus nec, pulvinar interdum sapien. Nunc porta mi eu elementum gravida.

Nulla et purus egestas, pellentesque odio a, tempus lorem. Phasellus sed vestibulum odio. Phasellus lacinia, est et tincidunt aliquam, dui libero consequat velit, imperdiet elementum nibh erat suscipit lacus. Nunc sodales condimentum mauris nec imperdiet. Pellentesque euismod sem posuere bibendum interdum. Curabitur elementum velit dolor, nec ornare tortor hendrerit non. Fusce nunc eros, consequat ac hendrerit non, tincidunt vel purus. Nullam eget mauris id nisl mattis pulvinar. Curabitur tincidunt elementum nibh, vitae cursus sapien fermentum vitae. Vestibulum est ante, hendrerit id mi non, molestie mollis ipsum.

Maecenas in ex sed odio fermentum ullamcorper nec sed felis. Suspendisse eu egestas felis, ut aliquam leo. In turpis felis, ultrices vitae sem eget, sagittis sagittis magna. Nulla vitae urna pharetra, ultrices purus nec, maximus enim. Quisque dapibus varius felis, quis volutpat odio euismod non. Fusce laoreet interdum dictum. In varius mi eget dui fringilla tincidunt. Nulla tincidunt tincidunt est, et sagittis massa lacinia sed. Aliquam ultricies orci vitae diam porttitor pellentesque. Maecenas non magna diam.

Aenean tincidunt purus et varius congue. Etiam vulputate, nisl sit amet pellentesque egestas, velit velit scelerisque sem, nec auctor velit lacus vitae orci. Proin aliquam congue consequat. Nullam vestibulum, nulla ac ultricies eleifend, tortor lorem dignissim ligula, finibus tempor massa leo vitae mauris. Integer ultrices mollis cursus. Phasellus dignissim a ex vitae condimentum. Aenean at tempor felis, et egestas ligula. Suspendisse purus magna, consequat non placerat id, tempus vitae lorem. Sed bibendum porttitor efficitur. Curabitur mattis massa vel eros interdum, at fringilla odio pharetra. Nulla fermentum efficitur laoreet. Maecenas nec gravida tortor.

Morbi tincidunt ex et nunc placerat, sed aliquam quam sagittis. Suspendisse risus lacus, pretium in nisi quis, auctor pulvinar mi. Suspendisse ac tristique ex. Quisque pretium dictum quam eget cursus. Aliquam ultrices mauris at pretium tincidunt. Quisque mattis ex a lorem facilisis fermentum. Aliquam venenatis nulla libero, luctus rutrum dui condimentum eget. Aenean quis nisi ut diam tempus porttitor eget id neque. Suspendisse lorem nulla, finibus vel tempus et, ullamcorper quis purus. Quisque id ipsum id odio dignissim faucibus et ut felis.

Sed interdum vel eros eget aliquet. Aenean congue congue ultrices. In elementum, leo eu ullamcorper auctor, nisl elit vehicula justo, ac aliquam nulla sem eget dui. Vivamus id laoreet arcu, sed cursus massa. Mauris interdum hendrerit enim quis dapibus. Integer ultricies tristique tortor eget facilisis. Nulla euismod turpis ex, non tristique lorem sagittis eget. Fusce sagittis volutpat scelerisque. Phasellus pellentesque lectus a lacus placerat fringilla. Fusce euismod feugiat massa, id dictum velit sagittis non.

Duis laoreet, dolor id dignissim tincidunt, ex nunc vestibulum libero, eu porttitor turpis neque vitae diam. In non laoreet augue. Quisque sed ligula purus. Sed sagittis a sem eget porta. Nullam nec sodales quam. Nunc et velit vehicula, bibendum tellus vel, molestie sapien. Nam ut leo mollis, pharetra nulla a, euismod neque. Duis pretium urna et dui consectetur condimentum. Donec sed facilisis purus.

Mauris ac ullamcorper nibh, in cursus metus. Phasellus a metus vitae turpis eleifend lacinia. Integer dignissim pretium velit id hendrerit. Proin vehicula nisi tincidunt tellus fringilla sollicitudin. Ut accumsan quis mi ut lacinia. Pellentesque quis nunc vestibulum, lobortis velit ut, tristique diam. Mauris ac aliquam augue.

Duis erat magna, efficitur ac consequat finibus, vulputate nec mi. Aliquam convallis nisi quis libero mattis ultricies. Donec accumsan sem vitae justo mattis, id ultrices turpis interdum. Curabitur iaculis est et semper molestie. Quisque tempus interdum pretium. Phasellus et mauris in quam euismod tempus. Nunc et lorem vel justo pulvinar aliquam. Cras dapibus urna a tempus facilisis. Duis non commodo nisl. Sed nec purus ac erat pharetra volutpat nec sit amet elit. Vivamus at porttitor dui. Curabitur dui nibh, viverra quis ipsum vitae, congue scelerisque nunc. Proin fringilla venenatis rutrum. Nulla lectus ex, semper non mi vel, ultricies aliquam ex. Duis a nisl quis metus pharetra molestie placerat quis elit. Duis eleifend odio ac risus sollicitudin condimentum.

Etiam in rutrum metus. Aliquam consectetur magna lectus, sagittis euismod purus hendrerit et. Pellentesque ut orci sit amet nisi varius aliquam ac ut dui. Suspendisse consectetur vulputate suscipit. Nulla ut mattis arcu. Integer justo odio, aliquet in pharetra et, mattis vel sem. Praesent viverra interdum pretium. Aenean elementum efficitur sodales. Nullam vestibulum leo odio.

Cras aliquam auctor venenatis. Donec ligula dolor, aliquet ut nisi at, malesuada viverra sapien. Vivamus in viverra sapien, at consequat nibh. Aliquam vestibulum in leo in dignissim. Cras eu hendrerit dolor, in euismod risus. Sed sollicitudin nulla eget augue eleifend, et aliquet diam sodales. Etiam vehicula, nisi a sagittis maximus, sapien tellus consectetur ipsum, volutpat fermentum turpis justo et magna. Fusce sodales interdum ex sed suscipit.

Etiam lacinia velit orci, ut placerat sem sollicitudin eget. In a imperdiet lacus, in ullamcorper erat. Sed posuere odio ut lorem egestas malesuada. Donec id libero tempus, commodo magna quis, vulputate purus. Morbi accumsan fringilla ante, quis bibendum orci fringilla et. Sed posuere consequat diam et mattis. Nunc sit amet augue porttitor, venenatis massa eu, faucibus justo. Morbi venenatis iaculis sem eget facilisis.

Nullam porta pharetra eros id euismod. Maecenas quis suscipit odio, a accumsan lorem. Mauris suscipit, eros ac hendrerit sagittis, felis lorem hendrerit ligula, id consectetur justo diam eget turpis. Vivamus scelerisque enim ut condimentum ultrices. Mauris tempus bibendum vehicula. Sed quis sapien rhoncus, mattis nisl eget, cursus ante. Vestibulum malesuada, ligula ut accumsan pharetra, nulla orci pellentesque risus, quis tempor neque tortor a mauris. Aliquam nec consectetur mi. Phasellus non quam eu ex facilisis malesuada quis id arcu. Nam sodales quam sit amet arcu varius feugiat non ut nisi. Sed turpis orci, molestie vulputate orci sit amet, sollicitudin malesuada ex. Praesent condimentum velit sit amet nunc fermentum porttitor. Cras est nisi, pretium in sapien varius, imperdiet vehicula lectus. Suspendisse faucibus est eget pharetra vulputate.

Integer rutrum mauris vehicula lobortis ornare. Vivamus vehicula velit ac sodales interdum. Duis sem ipsum, volutpat at tempus vel, ullamcorper egestas risus. Pellentesque pretium nisi in commodo iaculis. Fusce consectetur ligula in vestibulum condimentum. Pellentesque eget bibendum sem. In hac habitasse platea dictumst. Curabitur placerat pellentesque nisi, sed imperdiet metus. Duis ornare augue ipsum.
    </div>

  return (
    <main>
      <ContentBlock className={styles.lander} content={content}/>
     </main>
  );
};